### ISSUE TITLE
Exceptions being swallowed

### ISSUE THREAD

**Issue by CoskunSunali** [sebastienros/yessql#144]
This is semi-related to #131.

Whenever an exception occurs while creating tables or processing a command, the exception is being lost and a generic exception message is shown.

```
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at YesSql.Session.Dispose() in D:\work-external\github\CoskunSunali\yessql\src\YesSql.Core\Session.cs:line 437
   at YesSql.Store.InitializeAsync() in D:\work-external\github\CoskunSunali\yessql\src\YesSql.Core\Store.cs:line 115
   at YesSql.Samples.Web.Controllers.HomeController.Index() in D:\work-external\github\CoskunSunali\yessql\samples\YesSql.Samples.Web\Controllers\HomeController.cs:line 20
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

This can easily be replicated. Calling `store.InitializeAsync()` twice in a row first throws an exception internally (considering that schema already exists), and then `Session` class tries to commit the transaction while disposing itself but the transaction is already zombied.

Real exception at `SchemaBuilder.CreateTable`:

![image](https://user-images.githubusercontent.com/6509380/50881564-10b83880-13f3-11e9-90fa-c39fc3100969.png)

YesSql tries to dispose session that it created in `InitializeAsync`, dispose doesn't check if an exception occured and tries to commit the transaction.

![image](https://user-images.githubusercontent.com/6509380/50881742-a784f500-13f3-11e9-975e-f7be6378c22e.png)

The exception is totally different in the `finally` section because `Commit` caused another exception.

![image](https://user-images.githubusercontent.com/6509380/50881875-02b6e780-13f4-11e9-8717-f7daa5ec88ab.png)

Final result:

![image](https://user-images.githubusercontent.com/6509380/50881900-17937b00-13f4-11e9-9d53-81245fd498f9.png)

**Comment by sebastienros** [comment]
Fixed by #154
