### ISSUE TITLE
Error on Alter column sql generated

### ISSUE THREAD

**Issue by jersiovic** [sebastienros/yessql#244]
With sqlite it seems Alter Column commnad doesn't seems to generate a valid sql.

This SchemaBuilder command:

```
using (var transaction = connection.BeginTransaction(_store.Configuration.IsolationLevel))
                {
                    var builder = new SchemaBuilder(_store.Configuration, transaction);
                    builder.AlterTable(nameof(UserByRoleNameIndex), column => column
                            .AlterColumn(nameof(UserByRoleNameIndex.RoleName), column => column.WithType(DbType.String, 100))
                        );
                    transaction.Commit();
                }
```
produced following sql:
`alter table [tpUserByRoleNameIndex] alter column [RoleName] TEXT COLLATE NOCASE`
Which fails, because it is not valid for sqlite and also which doen't takes into account the max length param

**Comment by jersiovic** [comment]
With MySQl it works without problems.
But I see PostgesSql also fails, for different reason

This is the sql it produces:
`alter table "tpUserByRoleNameIndex" modify column "RoleName" varchar(100)`

and it produces a sintax error due to "modify"

**Comment by jersiovic** [comment]
For SqlServer it works properly

**Comment by jersiovic** [comment]
I've just fixed Postgressql issue locally. I can provide PR, but also would like  to provide a fix for Sqlite.
Problem I see is read here https://www.techonthenet.com/sqlite/tables/alter_table.php it is not supported 
"You can not use the ALTER TABLE statement to modify a column in SQLite. Instead you will need to rename the table, create a new table, and copy the data into the new table."

So, should YesSql do that job internally?

**Comment by KeithRaven** [comment]
I have a similar issue when running against Sqlite.  The following command fails in a OC migration:

```
                SchemaBuilder.AlterIndexTable<AuditTrailEventIndex>(table =>
                    table.AlterColumn(nameof(AuditTrailEventIndex.CorrelationId), clm => clm.WithType(typeof(string), 64)), "Audit"
                );
```

with the exception message: SQLite Error 1: 'near "alter": syntax error'.

The reason I believe is that Sqlite does not recognise column length.  I therefor had to make the AlterIndexTable command condition base on SchemaBuilder.Dialect.Name. The command runs fine against SqlServer.

**Comment by deanmarcussen** [comment]
See also https://github.com/sebastienros/yessql/issues/380

Not quite your issue @KeithRaven but we toook a new version of the sqlite driver a couple of days ago, so worth seeing what batteries is loading now.

Equally the dialect could support column lengths, it's just a lot trickier for the dialect to support the drop column issue the @jersiovic originally report

**Comment by sebastienros** [comment]
@KeithRaven probably something to fix in YesSql. Can you file an issue, and if I am allowed to ask, provide a PR?

**Comment by KeithRaven** [comment]
@sebastienros Thanks. When I find a moment I'll take a closer look and file a more detailed issue.  If I can I'll do a PR, no promises though :)

**Comment by hyzx86** [comment]
I have a similar issue when running against postgres . 

This is what I wrote initially

```C#
         SchemaBuilder.AlterIndexTable<AuditTrailEventIndex>(table => table
                        .AlterColumn(nameof(AuditTrailEventIndex.CorrelationId),
                            column => column.WithType(typeof(string), 255)),
                    collection: AuditTrailEvent.Collection
                );
```


```
Error while running migration version 0 for 'EasyOC.AuditTrail'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "modify"

POSITION: 42
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|221_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2848
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at YesSql.Sql.SchemaBuilder.Execute(IEnumerable`1 statements)
   at YesSql.Sql.SchemaBuilder.AlterTable(String name, Action`1 table)
   at YesSql.Sql.SchemaBuilder.AlterIndexTable(Type indexType, Action`1 table, String collection)
   at EasyOC.AuditTrail.Migrations.UpdateAuditTrailMigrations.Create() in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC\src\Modules\EasyOC.AuditTrail\Migrations\UpdateAuditTrailMigrations.cs:line 30
  Exception data:
    Severity: ERROR
    SqlState: 42601
    MessageText: syntax error at or near "modify"
    Position: 42
    File: scan.l
    Line: 1133
    Routine: scanner_yyerror
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)
```

And then I tried to change it to `WithLength`
```C#

                SchemaBuilder.AlterIndexTable<AuditTrailEventIndex>(table => table
                        .AlterColumn(nameof(AuditTrailEventIndex.CorrelationId),
                            column => column.WithLength(255)),
                    collection: AuditTrailEvent.Collection
                );
```


```
Error while running migration version 0 for 'EasyOC.AuditTrail'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "modify"

POSITION: 42
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|221_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2848
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at YesSql.Sql.SchemaBuilder.Execute(IEnumerable`1 statements)
   at YesSql.Sql.SchemaBuilder.AlterTable(String name, Action`1 table)
   at YesSql.Sql.SchemaBuilder.AlterIndexTable(Type indexType, Action`1 table, String collection)
   at EasyOC.AuditTrail.Migrations.UpdateAuditTrailMigrations.Create() in D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC\src\Modules\EasyOC.AuditTrail\Migrations\UpdateAuditTrailMigrations.cs:line 30
  Exception data:
    Severity: ERROR
    SqlState: 42601
    MessageText: syntax error at or near "modify"
    Position: 42
    File: scan.l
    Line: 1133
    Routine: scanner_yyerror
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)
```

**Comment by rwawr** [comment]
I'm running into a similar issue trying to write a migration in Orchard Core 2.2.0 to increase the length of a column.

I originally tried
```
await SchemaBuilder.AlterTableAsync(
    nameof(TokenRecord),
     table => table.AlterColumn(nameof(TokenRecord.Data), col => col.WithLength(2500)));
```
which seemed to work fine in SQLite, but resulted in the following exception in SQL Server
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Implicit conversion from data type nvarchar to varbinary is not allowed. Use the CONVERT function to run this query.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 662
   at YesSql.Sql.SchemaBuilder.ExecuteAsync(IEnumerable`1 statements)
   at YesSql.Sql.SchemaBuilder.AlterTableAsync(String name, Action`1 table)
```

Changing it to 
```
await SchemaBuilder.AlterTableAsync(
    nameof(TokenRecord),
     table => table.AlterColumn(nameof(TokenRecord.Data), col => col.WithType((typeof(string), 2500)));
```

makes it work fine in SQL Server but fail with the following error in SQLite

```
2025-10-24T14:05:40.9755211-04:00||0HNGJ4PKQCVBB:00000007|OrchardCore.Data.Migration.DataMigrationManager|ERR|Error while running migration version 1 for 'Cider.Tokenization'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "alter": syntax error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 662
   at YesSql.Sql.SchemaBuilder.ExecuteAsync(IEnumerable`1 statements)
   at YesSql.Sql.SchemaBuilder.AlterTableAsync(String name, Action`1 table)
```

**Comment by sebastienros** [comment]
@rwawr what is the initial type/length of TokenRecord.Data ?

**Comment by rwawr** [comment]
@sebastienros The initial type is string and the initial length is 255, which was just the default, as I hadn't specified a length for the column when creating it. My original `CreateTableAsync` call looked like this:

```
await SchemaBuilder.CreateTableAsync(nameof(TokenRecord), table => table
    .Column<long>(nameof(TokenRecord.Id), col => col.PrimaryKey().Identity())
    .Column<string>(nameof(TokenRecord.Data), col => col.NotNull())
    [MoreColumns]
```
