### ISSUE TITLE
Thread safety in YesSql (SQL Server)

### ISSUE THREAD

**Issue by DAud-IcI** [sebastienros/yessql#271]
We had some true multi-threaded code using YesSql, like multiple queries with different parameters that were awaited parallel via Task.WhenAll. It works well using SQLite but the same queries cause strange, hard to debug issues in SQL Server such as
```
2020-09-08 15:21:18.8555|Default||42ebf0d2-4f46c68409f05a6d.||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.ArgumentException: An item with the same key has already been added. Key: 2807
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at YesSql.Indexes.IdentityMap.AddEntity(int id, object entity)
   at YesSql.Session.Get[T](IList`1 documents)
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at [code inside async Select]
```
The log didn't capture line numbers but debug says the exception was here: https://github.com/sebastienros/yessql/blob/dev/src/YesSql.Core/Indexes/IdentityMap.cs#L29
Sorry, I wasn't able to create a synthetic example to reproduce it, even in our production code it only happened on about every 5-10th request when larger queries were involved so there is probably some timing aspect that I wasn't able to simulate.

Replacing WhenAll with sequential awaits seems to prevent the issue, but this seems like a source of danger. I wonder if locking inside YesSql.Session.Get could be a safer solution?

**Comment by Piedone** [comment]
The multi-threaded code used the same `ISession` instance, right?

**Comment by DAud-IcI** [comment]
Yes.

**Comment by sebastienros** [comment]
Then it's wrong. Each thread needs it's own session. Sessions are not thread safe. But yessql works fine as long as you have a session per thread. Transactions and concurrency options prevent any issues to happen in this case.
