### ISSUE TITLE
MapIndex could be resolve from a scoped service provider

### ISSUE THREAD

**Issue by HengzheLi** [sebastienros/yessql#321]
I add a index provider to the service provider with AddSingle(in OrchardCore CMS). Then I query the index with a session which is resolved from a scoped service provide. Then below exception is thrown:
```
Exception: 
System.InvalidOperationException: variable 'i' of type '[MyMapIndex]' referenced from scope '', but it is not defined
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.LambdaExpression.Compile()
   at YesSql.Services.DefaultQuery.Evaluate(Expression expression)
   at YesSql.Services.DefaultQuery.Evaluate(Expression expression)
   at YesSql.Services.DefaultQuery.<Evaluate>b__15_1(Expression a)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at YesSql.Services.DefaultQuery.Evaluate(Expression expression)
   at YesSql.Services.DefaultQuery.ConvertFragment(StringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.ConvertPredicate(StringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.ConvertEqualityBinaryExpression(StringBuilder builder, BinaryExpression expression, String operation)
   at YesSql.Services.DefaultQuery.ConvertFragment(StringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.ConvertPredicate(StringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.Filter[TIndex](Expression`1 predicate)
   at YesSql.Services.DefaultQuery.Query`1.YesSql.IQuery<T>.With[TIndex](Expression`1 predicate)
   at YesSql.QueryExtensions.Query[T,TIndex](ISession session, Expression`1 predicate, Boolean filterType, String collection)
```

Key code snippet is as blew:
```
var session = (ISession)serviceProvider.GetService<ISession>();
var currentOrders = await session.Query<ContentItem, [MyMapIndex]>(i => keyLogins.Contains(i.Login) && i.OpenTime >= openAfterEpoch)
                .With<ContentItemIndex>(i => i.Published && i.Latest && i.ContentType == Migrations.PricingOrderProcessInfoContentType)
                .ListAsync();
```

Any idea why the exception is thrown?

**Comment by deanmarcussen** [comment]
Bad code ;) 

remove the square brackets around `MyMapIndex`
and use the `IsIn` extension defined in `YesSql.Services`

```
var currentOrders = await session.Query<ContentItem, MyMapIndex>(i => i.Login.IsIn(keyLogins) && i.OpenTime >= openAfterEpoch)
                .With<ContentItemIndex>(i => i.Published && i.Latest && i.ContentType == Migrations.PricingOrderProcessInfoContentType)
                .ListAsync();
```

**Comment by HengzheLi** [comment]
Thanks. "IsIn" solves the problem.
