### ISSUE TITLE
Indexes with Enum Fields broken as of 9a8f24fe346f979f89af0dd1d1b925ec8eef5104

### ISSUE THREAD

**Issue by sfmskywalker** [sebastienros/yessql#323]
Before the changes introduced with 9a8f24fe346f979f89af0dd1d1b925ec8eef5104, the following index would work fine:

```csharp
public class ArticleIndex : MapIndex
    {
        public string Content { get; set; }
        public ArticleType ArticleType { get; set; }
        public DateTimeOffset PublishedAt { get; set; }
    }

public enum ArticleType
    {
        TypeA,
        TypeB
    }

public class Article
    {
        public string Content { get; set; }
        public ArticleType ArticleType { get; set; }
        public DateTimeOffset PublishedAt { get; set; }
    }
```

With the changes in 9a8f24fe346f979f89af0dd1d1b925ec8eef5104, the above fails with:

```
Unhandled exception. System.InvalidOperationException: This operation is only valid on generic types.
   at System.RuntimeType.GetGenericTypeDefinition()
   at YesSql.Sql.Schema.SchemaUtils.ToDbType(Type type) in C:\Projects\yessql\src\YesSql.Core\Sql\Schema\SchemaUtils.cs:line 42
   at YesSql.Commands.IndexCommand.GetProperties(DynamicParameters parameters, Object item, String suffix) in C:\Projects\yessql\src\YesSql.Core\Commands\IndexCommand.cs:line 59
   at YesSql.Commands.CreateIndexCommand.AddToBatch(ISqlDialect dialect, List`1 queries, DynamicParameters parameters, List`1 actions) in C:\Projects\yessql\src\YesSql.Core\Commands\CreateIndexCommand.cs:line 90
   at YesSql.Session.BatchCommands() in C:\Projects\yessql\src\YesSql.Core\Session.cs:line 851
   at YesSql.Session.FlushAsync() in C:\Projects\yessql\src\YesSql.Core\Session.cs:line 791
   at YesSql.Session.Dispose() in C:\Projects\yessql\src\YesSql.Core\Session.cs:line 649
   at YesSql.Samples.FullText.Program.Main(String[] args) in C:\Projects\yessql\samples\YesSql.Samples.FullText\Program.cs:line 63
   at YesSql.Samples.FullText.Program.<Main>(String[] args)
```

See [YesSql.Samples.FullText.zip](https://github.com/sebastienros/yessql/files/5761490/YesSql.Samples.FullText.zip) that reproduces the issue.

**Comment by deanmarcussen** [comment]
Also reported in OC https://github.com/OrchardCMS/OrchardCore/issues/8223

**Comment by sebastienros** [comment]
While working on a unit test, noticed how unfamiliar it looked like. Using an enum as an index type. Now I realize that you might be the only one who thought about doing something like this. I was expecting users to map the enum to a standard type in the mapping lambda. Like string of int. But I ma fixing it anyway, assuming it to be an integer like it was before the change, unwillingly. I assume Dapper was doing the mapping.

**Comment by sfmskywalker** [comment]
Maybe this is why my mom always tells me that I am a special kid. ;)
That being said, I'm OK doing the mapping as per recommendation. I just didn't know 🤷‍♂️
