### ISSUE TITLE
InvalidCastException: Failed to convert parameter value from a DateTimeOffset to a DateTime.

### ISSUE THREAD

**Issue by sfmskywalker** [sebastienros/yessql#325]
I haven't found a way yet to reproduce this in a sample application, but after updating to latest YesSql (2.0.0-beta-1677), I'm seeing this error:

```
System.InvalidCastException: Failed to convert parameter value from a DateTimeOffset to a DateTime.
 ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   --- End of inner exception stack trace ---
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteWrappedReaderImplAsync(IDbConnection cnn, CommandDefinition command, CommandBehavior commandBehavior) in /_/Dapper/SqlMapper.Async.cs:line 1135
```

My indexes do use DateTimeOffset, but that alone seems fine when I try with the FullText sample.
I'm continuing to look into this, but figured someone else might have seen this too and has a repro to share perhaps.

**Comment by sfmskywalker** [comment]
Here's the command of the operation:

```
insert into [WorkflowInstances_Document] ([Id], [Type], [Content], [Version]) values (@Id_0, @Type_0, @Content_0, @Version_0);
insert into [WorkflowInstances_WorkflowInstanceIndex] ([DefinitionId], [WorkflowStatus], [TenantId], [InstanceId], [Version], [CorrelationId], [ContextType], [ContextId], [Name], [CreatedAt], [LastExecutedAt], [FinishedAt], [CancelledAt], [FaultedAt], [DocumentId]) values (@DefinitionId1, @WorkflowStatus1, @TenantId1, @InstanceId1, @Version1, @CorrelationId1, @ContextType1, @ContextId1, @Name1, @CreatedAt1, @LastExecutedAt1, @FinishedAt1, @CancelledAt1, @FaultedAt1, @DocumentId1) ; select SCOPE_IDENTITY() [Id];
insert into [WorkflowInstances_WorkflowInstanceBlockingActivitiesIndex] ([TenantId], [ActivityId], [ActivityType], [CorrelationId], [WorkflowStatus], [CreatedAt], [DocumentId]) values (@TenantId2, @ActivityId2, @ActivityType2, @CorrelationId2, @WorkflowStatus2, @CreatedAt2, @DocumentId2) ; select SCOPE_IDENTITY() [Id];

```

It happens in `BatchCommand` on line 65:

`using (var dr = await connection.ExecuteReaderAsync(command, Parameters, transaction))`

Looking at the Parameters collection, I can see my documents containing date/time values, but interestingly enough their `DbType` is `DbType.DateTime`. Should this have been `DbType.DateTimeOffset` instead as per my index?

**Comment by sfmskywalker** [comment]
A screen capture:

![image](https://user-images.githubusercontent.com/938393/103648825-c0323200-4f5d-11eb-8fa8-20e908a0db1a.png)

**Comment by sfmskywalker** [comment]
As a work around, I updated my indexes to use `DateTime` instad of `DateTimeOffset`.
