### ISSUE TITLE
Extend Document.Id to long

### ISSUE THREAD

**Issue by Oceania2018** [sebastienros/yessql#435]
When I try to use Postgresql in OrchardCore, I encountered an issue like:
```
OrchardCore.Users.Services.UserStore|ERROR|Unexpected error while creating a new user. System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value)
   at YesSql.Commands.CreateIndexCommand.<AddToBatch>b__6_0(DbDataReader dr) in D:\EntityFlow\yessql\src\YesSql.Core\Commands\CreateIndexCommand.cs:line 96
   at YesSql.Commands.BatchCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger) in D:\EntityFlow\yessql\src\YesSql.Core\Commands\BatchCommand.cs:line 72
   at YesSql.Session.FlushAsync() in D:\EntityFlow\yessql\src\YesSql.Core\Session.cs:line 735
   at YesSql.Session.FlushAsync() in D:\EntityFlow\yessql\src\YesSql.Core\Session.cs:line 743
   at YesSql.Session.SaveChangesAsync() in D:\EntityFlow\yessql\src\YesSql.Core\Session.cs:line 864
   at YesSql.Session.SaveChangesAsync() in D:\EntityFlow\yessql\src\YesSql.Core\Session.cs:line 876
   at OrchardCore.Users.Services.UserStore.CreateAsync(IUser user, CancellationToken cancellationToken) in D:\EntityFlow\OrchardBoost\src\OrchardCore\OrchardCore.Users.Core\Services\UserStore.cs:line 113    at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
```
I've found the data type is mismatch:
![image](https://user-images.githubusercontent.com/1705364/160915947-43f68585-1415-4ddc-9c32-13dfa3899e2b.png)

@sebastienros Is it possible to extend the Document Id to `Int8`?

**Comment by CrestApps** [comment]
I think this should be a configurable option during initializing. In most case, `unsigned int` is enough and should be the default since it'll have the best performance "as far as I know". However, when one is expecting to store lots of data, using unsigned bigint, string or GUID may be the way to go. I am actually looking to use OrchardCore CMS in a very large project which is going to leads to lots of data being stored in the document table. In this case, utilizing at least unsigned bigint or string/GUID my be a must for me even if it comes with performance cost. 

But this also begs the question, how will the document table perform when you have over 9 quintillion records given that the content column is huge.

**Comment by Oceania2018** [comment]
There is a situation where new data is continuously generated and old data is deleted, which is not enough for a large project.
