### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Session'.

### ISSUE THREAD

**Issue by scil** [sebastienros/yessql#450]
recently, this error frequencly occured and led to `Process finished with exit code -532,462,766..

```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Session'.
   at YesSql.Session.CheckDisposed()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Users.Services.UserStore.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at My.Module.User.Controllers.UserSpaceController.QueryUser(String username) in K:\My.Module.User\Controllers\UserSpaceController.cs:lin
e 47

```

related code
```
        protected async void QueryUser(string username)
        {
            var user = await _userManager.FindByNameAsync(username) ;

        }

```

what is possible to cause this error?

**Comment by scil** [comment]
maybe sometime the `username` is null.
